env:
  global:
    - secure: hb40leQGTepBsxnj7Bs4f4OzE4dBespe92H8maPWwhrvfc5DerVKiPDzrhC9fm5EGQdfA4YX/4zKYmRQEgIrL6D2rpfxaB4m/FZY/hdVf89VFqzPHsUiSDL+vrXYU+d49dH103gOKRl3H7Jan/oR9eOTJLS9mS93z7y7aHO0qYhTLP+/Puvyw8IMD62Ebq3F03btjJVkw9XYyqJR4R36naQBeDLf6H1sMo/w2uwrqJhzu5Tn3CjC29b/M76UXX3wbvDvE0bF5Zj8QKwWEehI1NiolJxZHY6bibG5IUdxKRhsjYrngNpXBB4aazS/0m6PFb22wn1bafld/uKjzq0I5jyjy8XVFZdPrFrpq8dzxbwpvWJe3OPFFPSI5woOx5QfsL4eVUMJttWDJAuMiYmA8UwH9S1aW3nPCv0qWcjWDggWwb5rrVSxCg9ygDj9GKgv0I/n8DxywVk09rjrUxDYG186WRn1bqc6WLW4oyKZLDcoDlc2mpOzE0yFpI/5fU3K7Gt2fl8Em5WpPf+7ObgjuwyNK3+mYsjDBQF2y5BR2JZ2WOtL7Q0P2M4MlLFdIr7Ji2ZQbEdXa32XkN26b4B0a/cLRmjVw2nyNilhKV+4+QLqipM7VDjaDRUkQ43Di2qUUiR81d2v27739bkpYFQ98JqDmFvv8GE2Ul9cDp4OW5k=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: funilrys@outlook.com
    - TRAVIS_REPO_SLUG: dead-hosts/polish-adblock-filters_git_MajkiIT
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - sudo apt-get -y install python3-pip
  - sudo apt-get -y install dos2unix
  - pip3 install colorama

script:
  - export TRAVIS_BUILD_DIR=${TRAVIS_BUILD_DIR}
  - export GH_TOKEN=${GH_TOKEN}
  - export TRAVIS_REPO_SLUG=${TRAVIS_REPO_SLUG}
  - export GIT_EMAIL=${GIT_EMAIL}
  - export GIT_NAME=${GIT_NAME}
  - python3 ./update_me.py

notifications:
  email: false









nMQsFRRRXdC6Fcvqf0wA3X+0NG+C4/kN6fP2XPbVntYB+XkQ52dS5r+TRER9z70Ms/UMwqTshDBvTUCmBK2AB83Nakk6Hbzh3QM+7er905phxRGaDOmRZbE2GmqBSEBJ3jDS2erhAVGqlNR0uFt+iL2ODkfKKd37o854XAq926/MLqItgSJsUF4LAn+rsCaYr1hFlpBrF56Gld06666QQ+qU+4XKnuhGoaT24B0AVPTv+lXaEbnPrQivJSCVs+NoK+hTRBFV10FVO8SkHWFDO9GBikMwd7Zhy/EEP+3/veOnks74VK8MQP+psgXdA0lgti/CbxyMJdpppz960zLHKUBVG2qn9n8w3oGieSU96P8POiK7dG6YoWqd4be8Kh8Kljc4X7TO2jR18m1wAgqqbG5S/DbkEHRo+7k0on6sjDSXglc1U+54Wzf5gi/57xuMPtZpmxCHorGQhtp3VZucVY7t4yeemqI9Jdgm1WhwFIRNbJ4MUQxUgNH47vYu1R3l240gcooFZavOkbb6k8F9Yc8VNM41NrVnhscOyp33fqs4VCy1kG6xwBlSLNIRtBsMuF0TbN5cFzshGmnPOEGYp5JvWLQmwaarFpANnwHerCjAcIB4LFxeh8zuUfDtlVNe3cf9hsfmFUpAJt3YFeuz9VDDXFdCJOFYbhCIIKy/Pp0=
CAqERiDs1eeRXRs0HB+IiBO3aOasd8LIpDdGN9PrH7uPtMEgzcmuL2hOYTq9p/ZOyd6PrtW5LmNTGEvWhwFxebb1laSn4XigOX28VPz2aGQr2WH4xwp4uCvTlFuudyMtNfaj+Q6Voc0UimI/Yz+hcHHvEpw5EFyp1V4y87jurXv4DKEJDyygQI2irzDjjfgakJW0TUpOejD9MsQ9gPyWtPdby5//YhoJDcts5MVfmz0hmwp3eNyx6B64jxBvFdmATXKIq7gYGuMaVQHaEivjXu4BNdlCeToG0fxo6S4LDUNNAUXeHYaWtzUhRnwvwNgPMHJGsrX3NlRXybCL7SqLHwyMgbw7XNOxlhn3UxjSQmqVB8/fCW3TrYG1jKAYqsGtUo5aXcDbaPI0VfFx2Td5en2tkLQhsnUPg/TIk6ol0o/YBsEP6v4qyDemYCgA++/ffkvbKNWpBgJwwlWupDB2F2Wjtb0PL0lJggySWA6ZgxeBK6lDk6rMBlDw472EadSnnni4Rt1uHw76BtTNKCsORhVYHuu+vQMMnzIBzyXAGwBeJN3aFpaiEY9BK6uuyECl6/WUVFkRuoRHXOkOXvnLRty8P7uO+N7OoE8BgV5Noz9ZJ35YL/5VMFITC9nk6PLJQzUV6WeomSs6rpvVaiI6wzSkWJ7YQ3GvZ390HzKG2+0=
ICDRVmwxrUkhUdJBSNoFyRx5ub2LY54LsG5J/M2Tpiy3FWqX18yaW+HkYssqeY4OyUdNq7OyYTzbMfsXlyhVCsAxe4nwGMSpLaGHIPdpbUb2GwS0asiMlxGdPy7EAlAKAqlXRZIEE8RPvpMp27+VvB4ME5izLhP7T6oYpBxGxZJ3bM01Hk20mdUqOlBMR51viMMZYAWVoHal8IHBBQM/0qeowi0E6Fog7IWKTDV/cSIB9plc1S8EipfoUV67/+wvmD/r4aTIM09R0OvqDXPCZFPfcblf/S6j27kHRrlI9AFytM+jQ0e3So4RmAQm39IegIpq55w9sKGO6ResbApY83pjKNeuiNbRuh4JD8TUg/2kl/6uJ6Pz4Bru30Uez7bz1r9eL/W4riJnAlWJqQJ+/u0nRNcc5f1pdyXXNQJZLNs2tckWEs+comYmKvXcJyS2qCHPgu8ABzPb3ol0C6YlwK5sJM1LGzSEzJQAGiimGpEw/12YQaVazivgwVEOCSxwNcfGeXj8WRvRN6N4K2VdmInFz5owBpTwFqghN9/SO06IFQXUOtxtjP1l+iqDaGwdAIXDM1w31Wqg+szckLfVXVlGsogdH9UcPhOsBHync6rxHeWcg/bJc9d3li7rgoGRbsJv4HiGODZDvrjxXQyUkyYmd7n60O1bel12l6oZq/c=
